### ISSUE TITLE
Helpful repo

### ISSUE THREAD

**Issue by ncuillery** [awei01/react-jest-testing-illustration#1]
Hi,

Here is a short message to let you know that this repo was very helpful to me to understand how to mock sub-component.

Examples about `TestUtils.mockComponent` are very rare on the Internet.

Thank you dude !

**Comment by MitMaro** [comment]
I would also like to add my thanks. Although not the purpose of this repository it was invaluable in understanding how to mock sub-components.

Thanks you!

**Comment by awei01** [comment]
ok, great. glad it helped.
